### ISSUE TITLE
Incompatible with latest release of KeePass (2.36) 

### ISSUE THREAD

**Issue by gonzalu** [mitchcapper/KPEntryTemplates#28] opened 2017-09-28 02:23 UTC
Latest release of KeePass refuses to load the KPEntry plugin as incompatible.

**Comment by mitchcapper** [comment] 2017-09-28 16:50
Closed dupe of #17 not a bug you are using an old version.

**Closed by mitchcapper** 2017-09-28 16:50 UTC

**Comment by mitchcapper** [comment] 2017-09-28 16:51
Note if you follow the directions on that bug and still have an issue do please re-open it.

**Comment by gonzalu** [comment] 2017-09-28 19:22
Thank you... my bad. I downloaded 7.6 and I guess Windows did not replace the file in the directory :( I forced the delete of the old file and re-copied it and now works great. Sorry for the dupe also :) 

Thanks for your efforts.. .your plugin is invaluable for me :) 7.6 working fine!
