### ISSUE TITLE
Incompatible with 2.36

### ISSUE THREAD

**Issue by SavageCore** [mitchcapper/KPEntryTemplates#17] opened 2017-06-09 12:46 UTC
![keepass_2017-06-09_13-44-51](https://user-images.githubusercontent.com/171312/26975969-e2096f32-4d19-11e7-8357-1541bf25a431.png)

**Comment by Wild13c** [comment] 2017-06-09 18:39
Mitch,
 I emailed Dominik about this and here is his response.
 
Dominik Reichl  -  9 minutes ago      
Apparently KPEntryTemplates 7.3 uses the EntryListForm class, which has been replaced by a more powerful **ListViewForm class in KeePass 2.36**. It should be easy to update the plugin to use the new ListViewForm class.

Best regards,
 Dominik

**Comment by mitchcapper** [comment] 2017-06-09 18:42
Hrm will try to update it although sounds like will have to fork the plugin for the pre /post 2.36 plugins.

**Comment by Wild13c** [comment] 2017-06-09 18:50
Thanks Mitch.  I love the KPET plugin.  It is why I use Keepass!

**Comment by sergeevabc** [comment] 2017-06-09 23:42
Any ETA?

**Comment by mitchcapper** [comment] 2017-06-10 01:07
Pretty bogged down with work, so I would guess several weeks before I could start looking.  Unfortunately, I also operate on a fork of the keepass base code which makes updating more work.

**Comment by mitchcapper** [comment] 2017-06-10 01:07
Hrm, there do seem to be several people commenting here however, I will see if I can take a look next weekend.  If it is a simple fix I will try to implement then.

**Comment by MarkCanada** [comment] 2017-06-10 01:28
That would be great - thank you

**Comment by tiborauer** [comment] 2017-06-10 07:24
Thank you!

**Comment by ZorakIT** [comment] 2017-06-10 17:46
Thanks for your work!

**Comment by stbxxl** [comment] 2017-06-10 23:10
Many thanks for taking a look. I'm holding back with the update to 2.36 because your plugin won't work. I hope don't have to spend too much time to get it updated.

**Comment by aFooBar** [comment] 2017-06-11 00:27
Thanks for your work and taking time to update your plug-in

I don't understand why KPET is still not natively included in KP; without KPET, KP is nearly useless (that's of course my personnal POV ;-)

**Comment by Wild13c** [comment] 2017-06-11 02:10
aFooBar,  you're not by yourself in your POV.  As I stated earlier, "Thanks Mitch. I love the KPET plugin. **It is why I use Keepass!"**

**Comment by cieslickim** [comment] 2017-06-11 13:41
Dear Mitch,

Thanks for your great work. I understand how it is running short on time, anyway, just wanted to motivate you slightly, saying loud, that another happy user benefits from your plugin :-)

**Comment by jschof** [comment] 2017-06-12 00:59
I echo those sentiments!!!

**Comment by schossel** [comment] 2017-06-12 09:27
Thanks for your work, it's much appreciated! Keepass is much easier to use with your plugin!

**Comment by Stonebiter** [comment] 2017-06-12 17:49
Mitch, thank you for your work!  I hope you will be able to update your Plugin to KeePass 2.36.
KPET makes KP2 much better!

**Comment by brazenhead** [comment] 2017-06-12 21:16
Thanks for all your work Mitch! Your efforts are really appreciated.

**Comment by mitchcapper** [comment] 2017-06-12 21:17
Thanks for all the support!  I do ask that comments be primarily related to furthering bugs however.  You are welcome to emoji over any items, but comments instantly email everyone watching this thread for updates.

**Comment by mitchcapper** [comment] 2017-06-13 01:18
Alright there is a fix in place those of you whom are able to compile or make your own plugins can test it:
https://github.com/mitchcapper/KPEntryTemplates/tree/kp_236_compat_pr

I will be doing a proper release when I hear about from Dominik if I can avoid having to fork the plugin for pre/post 2.36.

**Comment by persoderman** [comment] 2017-06-13 13:54
Looking forward to get an update when we can expect a new release for this plugin. This is one of the best plugin for KP. One question: When an update will be available I assume the data and the already created template will work as it did for 2.35 or do we need to recreate template and data?

**Comment by mitchcapper** [comment] 2017-06-13 17:38
Correct there is no data loss.  As for when sadly there is not an easy compiler option to support both old and new releases of KP so I may try to see if I can hack together a method that works.

**Comment by mitchcapper** [comment] 2017-06-13 18:35
Should be fixed: https://github.com/mitchcapper/KPEntryTemplates/releases/tag/7.5 works for all keepass verisons.

**Closed by mitchcapper** 2017-06-13 18:35 UTC

**Comment by schossel** [comment] 2017-06-13 18:44
Seems to be working as fas as I could test. Thank you!

**Comment by Wild13c** [comment] 2017-06-13 18:57
Mitch, 1st Thank you..  7.5 is Also working here on Win7 64 bit.    I have 2 questions for you.
1)  Is there any way to give the templates a name.  This would make identifying which one to use.  i.e say for credit cards, bank accounts, etc.
2) I would like to send you a donation.  Do you have a way for me to do that?

**Comment by tiborauer** [comment] 2017-06-13 19:02
Thank you for the quick fix!
Also working on Win10Pro 64bit.

**Comment by mitchcapper** [comment] 2017-06-13 19:03
@Wild13c 
1) Yes whatever title you specify on the template should show up when you go to select the template parent.

2) Not really, just bitcoin and I technically square cash.me sorry!

**Comment by persoderman** [comment] 2017-06-13 20:29
Great, working fine on Win10pro.

**Comment by jschof** [comment] 2017-06-13 20:35
Not sure if this was happening before but now when you edit an entry and you click on the X button in the top right corner of the window you are prompted with 

> Do you want to save the changes you have made to this entry?

even though no changes were made. I tried doing the same without the plugin installed and the behaviour is NOT the same. You are only prompted when you actually make changes to the entry.

Easy enough to ignore but thought I'd bring it to your attention in case something is not behaving the way you expected.

BTW Thanks for the quick turnaround w/ the new plugin!

**Comment by mitchcapper** [comment] 2017-06-13 20:40
@jschof please file a new bug on that.  The plugin should not make any changes (except for the first time the template parent is set or if you edit anything).  I cannot repro with the official build either with a quick test.  No code changed that should cause that to occur happened in the new version (the only thing that really changed is the template parent selector).  One item to watch would be the strings on the entry when it says that and if you hit no what the original strings look like.
.

**Comment by Wild13c** [comment] 2017-06-14 22:43
Mitch,  I was not sure where to ask this ?  Would it be possible/feasible to create an Export plugin that would export all of the KPET fields with data and then be able to Import the data back into a clean Keepass install.  The reason I am asking is I have been trying to figure out how to change the original fields I used in Keepass when I  imported my data using .csv format.  My thought would be to Export the data, then modify in .csv format to correct any fields that need to change and then Import it back to Keepass using a new template with the correct field names.  I would like to thank you again for the quick response and solution you have provided with the KPET 7.5 plugin.

**Comment by mitchcapper** [comment] 2017-06-14 22:45
@Wild13c  yes please do not reply on a ticket unrelated you email a lot of people every time you do.  KPET does not do anything magical, you can 100% export the data, modify the CSV columns, update the template and re-import.   KPET itself is not required to do the export as it just stores your data in the strings themselves.

**Comment by mosart** [comment] 2017-08-24 08:18
Dear Mitch,

Thanks for your great work. I see that I have the same error message. I guess you could not reproduce the error. So, What happens next?

**Comment by mitchcapper** [comment] 2017-08-24 14:45
You should download the new version or follow my instructions above about setting up a clean copy.  Everyone who has this bug did not use the newer version.
