### ISSUE TITLE
Not compatible with 2.39.1?

### ISSUE THREAD

**Issue by segdy** [mitchcapper/KPEntryTemplates#43] opened 2018-05-23 04:36 UTC
I just upgraded to latest 2.39.1 and I get the following error when starting KeePass:

![kpentrytemplates](https://user-images.githubusercontent.com/7464149/40403661-1acf0c8c-5e08-11e8-8b82-ad3dd4194118.png)

This is one of my most used plugins - it would be amazing if it would be compatible with newest KP!

**Comment by mitchcapper** [comment] 2018-05-23 05:09
dupe of #35 see pr #39 for the beta of the new version.

**Closed by mitchcapper** 2018-05-23 05:09 UTC
