### ISSUE TITLE
Incompatible with KeePass 2.39

### ISSUE THREAD

**Issue by mydexterid** [mitchcapper/KPEntryTemplates#35] opened 2018-05-06 11:13 UTC
Latest release (7.6) is incompatible with KeePass 2.39.

**Comment by Suncatcher** [comment] 2018-05-06 12:33
Confirm this.

![image](https://user-images.githubusercontent.com/6388034/39673327-c3e580a8-5142-11e8-84d1-ae1df65a4760.png)

**Comment by mitchcapper** [comment] 2018-05-06 13:57
Thanks, this is confirmed as a valid bug KP changed something with the text entry box and I have been working to see about the next version still being compatible with < 2.39.  Will hopefully have an update within the next few weeks.

**Comment by SanchoandPancho** [comment] 2018-05-06 17:31
Hello,
sorry for my bad english. If it it possible, I wish an option to drag and drop the entries into formulars, because the order of formular fields in for e.g. registration formulars differs - and auto-fill doesn't fills correctly. I make a suggestion, because you're already make the plugin working for the new version and than its maybe possible to make drag and droppable.

Thanks.

**Comment by Suncatcher** [comment] 2018-05-06 17:51
@SanchoandPancho you should create a new issue for this. This issue is purely incompatibility-wise

**Comment by TehPsychedelic** [comment] 2018-05-07 01:26
Alright back to 2.38. Don't know about you guys but this plugin is basically the difference between a regular "nice try open source" application and a real proper competitor to 1Password and the real guys.

**Comment by mitchcapper** [comment] 2018-05-07 04:48
Sorry! will hopefully have a new version out soon.

**Comment by mitchcapper** [comment] 2018-05-11 06:14
Please test the sample plgx have in #39   assuming it goes well in test I will push the official version within the next few days.

**Comment by Suncatcher** [comment] 2018-05-24 11:38
Still not released?

**Comment by Michael833** [comment] 2018-05-25 13:36
Does Dominik keep changing something that's breaking updates? So sorry, I know that updating can be annoying. Thank you for trying, we appreciate it.

**Comment by mitchcapper** [comment] 2018-05-25 16:07
It was a breaking change in keepass that caused the incompatibility, they do not happen that often.   You can download the package in #39 the second comment that works 100% with 2.39.1.  The problem is the there are several other bugs that have been pointed out I want to try to fix before the next official release and some of them are a bit more puzzling so I have been having a hard time isolating the best solution.

**Comment by bmix** [comment] 2018-06-23 19:31
I had installed the beta from above and all was functioning. Then I rebooted the machine and I got the error again (strange enough), that is the reason for this current issue. I now downloaded the latest release from June 16 and I still get this error. I am using KeePass 2.39.1 on Win10.

**Comment by tobby88** [comment] 2018-06-26 09:57
@bmix Works without problems here... Are you sure you used the right download? https://github.com/mitchcapper/KPEntryTemplates/files/1994132/KPEntryTemplates.zip

**Comment by bmix** [comment] 2018-06-27 11:00
Hmm... it seems I had another version. I just installed the one you linked to, and now all works fine! Thank you! Issue resolved for me.

**Comment by linkp** [comment] 2018-07-03 03:03
New version is working fine for me on Ubuntu, but not Debian
KPEntryTemplates.plgx file is same file on both machines. The plugins folder is symlinked to an ownCloud directory and it worked with the old version on both platforms until I installed the new test version of the plugin to fix the problem with 2.39.1 on Ubuntu. This version then broke the plugin on 2.35 for Debian, so I upgraded the Debian version to 2.39.1 from the testing (Buster) repository, but the plugin still fails.

I have another plgx plugin (KeeAgent) that is still working, (and the previous version of this plugin worked) so I don't suspect a missing Mono package.

Ubuntu 16.04.4 LTS Xenial using jtaylor PPA
keepass2:all/xenial 2.39.1+dfsg-1~ubuntu16.04~ppa1 uptodate

Debian 9.4 Stretch tested on both stable and testing packages
stable (Stretch): 2.35+dfsg-2
testing (Buster): 2.39+dfsg-1

**Comment by nagyalex** [comment] 2018-07-18 15:47
I updated to https://github.com/mitchcapper/KPEntryTemplates/files/1994132/KPEntryTemplates.zip with Keepass 2.3.91. First error was shown.

Then I noticed for some reason I had copies of KPEntryTemplates.plgx in main program directory. After deleting them it works smoothly on Win 7.

**Comment by Suncatcher** [comment] 2018-08-19 06:39
So what about update? For how long we should use dev release?

**Comment by jcamp** [comment] 2018-08-23 06:14
Is there going to be a new release? The fix works so why not put into production?

**Comment by mitchcapper** [comment] 2018-09-12 23:48
I committed some layout changes for keepass resize earlier but didn't test them as I didn't use that plugin.  After testing it I found it is actually working pretty poorly and may degrade the normal UX.  It is hard to test given some DPI requirements and the hardware I have access to currently.   

As such I haven't released the update.  I might just roll back the other commits to get it out.

**Comment by marcosimonegili** [comment] 2018-10-02 12:27
> I updated to https://github.com/mitchcapper/KPEntryTemplates/files/1994132/KPEntryTemplates.zip with Keepass 2.39.1. First error was shown.
> Then I noticed for some reason I had copies of KPEntryTemplates.plgx in main program directory. After deleting them it works smoothly on Win 7.

This version (7.8.0.0) of the Plugin also works on Win10 on KeePass 2.39.1 - Waiting for an official release! :)

**Comment by EdgewalkerBlue** [comment] 2018-10-02 13:00
> > I updated to https://github.com/mitchcapper/KPEntryTemplates/files/1994132/KPEntryTemplates.zip with Keepass 2.39.1. First error was shown.
> > Then I noticed for some reason I had copies of KPEntryTemplates.plgx in main program directory. After deleting them it works smoothly on Win 7.
> 
> This version (7.8.0.0) of the Plugin also works on Win10 on KeePass 2.39.1 - Waiting for an official release! :)

This version (7.8.0.0) of the Plugin also works on Win10 on KeePass 2.40

**Comment by cpalm1974** [comment] 2018-12-06 15:52
Could you please issue a new release for the current KeePass version? 
Now after so many months I found out that there is this working developer version. However I can't find a reason why this is not published so far as the GUI looks fine for me (although I haven't looked at it for almost a year now since upgrading to KeePass 2.39...).
Could you please give a hint in the readme.md for all for users that are forwarded to here from keepass.info since it gives the impression that KPEntryTemplates is a dead project (with the latest official release not working).

**Comment by mc0e** [comment] 2019-04-11 15:20
I'm also getting a compatibility error, but in my case I'm running KeePass 2.35, so either there's both backwards and compatibility issues, or there's something more going on.  The release notes suggest it should be backwards compatible.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment] 2019-05-26 16:42
![image](https://user-images.githubusercontent.com/46166740/58384753-f7044000-7fe5-11e9-9f05-ac33b2a18ca9.png)



```
[Window Title]
KeePass

[Content]
Folgendes Plugin ist inkompatibel mit der aktuellen KeePass-Version:
C:\Program Files (x86)\KeePass Password Safe 2\Plugins\KPEntryTemplates.plgx

Besuchen Sie die Plugins-Webseite für eine entsprechende Version.

[Expanded Information]
Der Vorgang ist aufgrund des aktuellen Zustands des Objekts ungültig.
KeePass
   bei KeePass.Plugins.PlgxPlugin.Compile(String strTmpRoot, PlgxPluginInfo plgx, String strBuildPre, String strBuildPost)
   bei KeePass.Plugins.PlgxPlugin.ReadFile(BinaryReader br, PlgxPluginInfo plgx, IStatusLogger slStatus)
   bei KeePass.Plugins.PlgxPlugin.LoadPriv(String strFilePath, IStatusLogger slStatus, Boolean bAllowCached, Boolean bAllowCompile, Boolean bAllowLoad, TextWriter twLog)
   bei KeePass.Plugins.PlgxPlugin.Load(String strFilePath, IStatusLogger slStatus)
System.String Compile(System.String, KeePass.Plugins.PlgxPluginInfo, System.String, System.String)

[^] Details  [OK]
```

**Closed** 2019-06-08 07:13 UTC
Labels: bug
