### ISSUE TITLE
Th efollowing plugin is incompatible with KeePass

### ISSUE THREAD

**Issue by MIGNA** [mitchcapper/KPEntryTemplates#26] opened 2017-07-12 11:57 UTC
Hello there, 

when launching KeePass 2.36 with the last version of this plugin, I get the following error :

![image](https://user-images.githubusercontent.com/21828359/28115818-b0493aac-6706-11e7-8635-4469e898f91c.png)

Thank you for your help.

**Comment by mitchcapper** [comment] 2017-07-12 14:44
hrm...  It has been tested with the latest version.  You sure you downloaded: https://github.com/mitchcapper/KPEntryTemplates/releases/download/7.6/KPEntryTemplates.plgx ?

If so can you run with the plugin debug `--debug`

**Comment by MIGNA** [comment] 2017-07-12 14:53
I get the log : 

Compiler 'v3.5':
...
error CS0006: Unable to find metadata file 'Microsoft.CSharp.dll'

**Comment by mitchcapper** [comment] 2017-07-12 15:16
What version of windows are you using.  Did you make sure you were using the 7.6 version of the plugin? Can you try upgrading your .net to the latest version.

**Comment by MIGNA** [comment] 2017-07-13 08:22
Hi, thank you for your responses. 
I'm on Windows 10, I'm sure of using the 7.6 version, re-download it from your link to be sure. 
I have .net framework 3.5 & 4.6, last updates, need them for work.

**Comment by MIGNA** [comment] 2017-07-17 11:27
Hello. Have you been able to think about why that doesn't work ? Am i the only one in this case ?

**Comment by mitchcapper** [comment] 2017-07-17 13:44
@MIGNA I cannot reproduce the issue currently and I have tested with Win10.  Others are also using the plugin.   We have some conferences for work for the next several weeks coming up so it may be awhile before I can try to see what else it could be.

**Comment by CWempe** [comment] 2017-07-19 19:03
Just had the same problem, but it turned out I had an older version of the rplugin installed.

Downloading from the Link above solved this. 👍 

KeePass 2.36
Win10 x64

**Comment by ghostku** [comment] 2017-07-26 00:36
Same issue
KeePass 2.36
Win10 x64

![image](https://user-images.githubusercontent.com/2576222/28599486-9b8e3fc4-71b3-11e7-8235-88480a3c3e9c.png)

**Comment by mitchcapper** [comment] 2017-07-26 00:37
@ghostku
Please provide the MD5 of the plgx file at c:\Progs\totalcmd\soft\!public\pass\kee...\KPEnryTemplates.plgx

**Comment by ghostku** [comment] 2017-07-26 00:38
44951b4815bd7cd7e814a46286c9e3b2 *KPEntryTemplates.plgx

**Comment by mitchcapper** [comment] 2017-07-26 00:41
If so can you run with the plugin debug  --debug 

does it give the same MIcrosoft.CSharp error?

**Comment by ghostku** [comment] 2017-07-26 00:47
I've got it.

So

It looks like they change plugin folder in some late release. Now you have `Plugins` folder where you should put your plugins, and I have most of my plugins in this folder, so I put KPEntryTemplate also in `/Plugins`. But you also have old plugins in the root folder, that's why it doesn't find a new plugin but the old one. Just move all `*.plgx` to `/Plugins` and that update them if needed.

**Comment by mitchcapper** [comment] 2017-07-26 00:50
Thanks for clarifying. 

Im closing this ticket due to people using the wrong version of the plugin.  If anyone feels they have an actual issue still then please do the following:
Download keepass portable and extract to:
c:\temp\keepass-TODAYS-DATE
ie:
c:\temp\keepass-2017-07-25
try the latest kpentrytemplates.plgx in that folder, if it shows the error please MD5 the exact path given by the error and run with --debug and provide that output.

**Closed by mitchcapper** 2017-07-26 00:50 UTC
